---
- hosts: remoteservers
  gather_facts: true
  remote_user: root
  tasks:
    - include_role:
        name: pre_install_checks
    - name: Check if google perf kit is already installed
      stat:
        path: /opt/googleperfkit
      register: application_directory
    - name: Download master branch of GooglePerfkit and unzip
      unarchive:
        src: https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/archive/master.zip
        dest: /opt/
        remote_src: yes
      when: application_directory.stat.exists == false
    - name: Rename downloaded archive
      command: mv /opt/PerfKitBenchmarker-master /opt/googleperfkit
      when: application_directory.stat.exists == false
    - name: Ansible check file exists example.
      stat:
        path: ~/.config
      register: oauth_directory
    - name: Make digital ocean config file directory
      file: path=~/.config state=directory
      when: oauth_directory.stat.exists == false
    - copy:
        src: ../passwords/digitalocean-oauth.curl
        dest: ~/.config/digitalocean-oauth.curl
    - copy:
        src: ../regions/digitalocean/2gb.yml
        dest: /root/2gb.yml
    - copy:
        src: ../regions/digitalocean/testpython.py
        dest: /root/testpython.py